/**
 * Elastic Email REST API
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a target=\"_blank\" href=\"https://api.elasticemail.com/public/help\">here</a>.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SubaccountEmailCreditsPayload model module.
 * @module model/SubaccountEmailCreditsPayload
 * @version 4.0.0
 */
class SubaccountEmailCreditsPayload {
    /**
     * Constructs a new <code>SubaccountEmailCreditsPayload</code>.
     * A change to SubAccount email credits pool, with an additional note.
     * @alias module:model/SubaccountEmailCreditsPayload
     */
    constructor() { 
        
        SubaccountEmailCreditsPayload.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SubaccountEmailCreditsPayload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubaccountEmailCreditsPayload} obj Optional instance to populate.
     * @return {module:model/SubaccountEmailCreditsPayload} The populated <code>SubaccountEmailCreditsPayload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubaccountEmailCreditsPayload();

            if (data.hasOwnProperty('Credits')) {
                obj['Credits'] = ApiClient.convertToType(data['Credits'], 'Number');
            }
            if (data.hasOwnProperty('Notes')) {
                obj['Notes'] = ApiClient.convertToType(data['Notes'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Positive or negative value; this will be added or subtracted from Subaccount's current email Credits pool.
 * @member {Number} Credits
 */
SubaccountEmailCreditsPayload.prototype['Credits'] = undefined;

/**
 * Note to append to this credits change, for history.
 * @member {String} Notes
 */
SubaccountEmailCreditsPayload.prototype['Notes'] = undefined;






export default SubaccountEmailCreditsPayload;

