/**
 * Elastic Email REST API
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://elasticemail.com/account#/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    This is the documentation for REST API. If you’d like to read our legacy documentation regarding Web API v2 click <a target=\"_blank\" href=\"https://api.elasticemail.com/public/help\">here</a>.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SubaccountEmailSettingsPayload from './SubaccountEmailSettingsPayload';

/**
 * The SubaccountSettingsInfoPayload model module.
 * @module model/SubaccountSettingsInfoPayload
 * @version 4.0.12
 */
class SubaccountSettingsInfoPayload {
    /**
     * Constructs a new <code>SubaccountSettingsInfoPayload</code>.
     * SubAccount settings
     * @alias module:model/SubaccountSettingsInfoPayload
     */
    constructor() { 
        
        SubaccountSettingsInfoPayload.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SubaccountSettingsInfoPayload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubaccountSettingsInfoPayload} obj Optional instance to populate.
     * @return {module:model/SubaccountSettingsInfoPayload} The populated <code>SubaccountSettingsInfoPayload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubaccountSettingsInfoPayload();

            if (data.hasOwnProperty('Email')) {
                obj['Email'] = ApiClient.convertToType(data['Email'], SubaccountEmailSettingsPayload);
            }
        }
        return obj;
    }


}

/**
 * Settings related to sending emails
 * @member {module:model/SubaccountEmailSettingsPayload} Email
 */
SubaccountSettingsInfoPayload.prototype['Email'] = undefined;






export default SubaccountSettingsInfoPayload;

