/**
 * Elastic Email REST API
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class TemplateType.
* @enum {}
* @readonly
*/
export default class TemplateType {
    
        /**
         * value: "RawHTML"
         * @const
         */
        "RawHTML" = "RawHTML";

    
        /**
         * value: "DragDropEditor"
         * @const
         */
        "DragDropEditor" = "DragDropEditor";

    
        /**
         * value: "LandingPageEditor"
         * @const
         */
        "LandingPageEditor" = "LandingPageEditor";

    
        /**
         * value: "TemplateEditor"
         * @const
         */
        "TemplateEditor" = "TemplateEditor";

    
        /**
         * value: "FormTemplate"
         * @const
         */
        "FormTemplate" = "FormTemplate";

    
        /**
         * value: "LandingPageTemplate"
         * @const
         */
        "LandingPageTemplate" = "LandingPageTemplate";

    
        /**
         * value: "PaymentConfirmationTemplate"
         * @const
         */
        "PaymentConfirmationTemplate" = "PaymentConfirmationTemplate";

    
        /**
         * value: "LandingPageProductTemplate"
         * @const
         */
        "LandingPageProductTemplate" = "LandingPageProductTemplate";

    
        /**
         * value: "LandingPageCheckoutTemplate"
         * @const
         */
        "LandingPageCheckoutTemplate" = "LandingPageCheckoutTemplate";

    
        /**
         * value: "LandingPagePaymentConfirmationTemplate"
         * @const
         */
        "LandingPagePaymentConfirmationTemplate" = "LandingPagePaymentConfirmationTemplate";

    

    /**
    * Returns a <code>TemplateType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/TemplateType} The enum <code>TemplateType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

