/**
 * Elastic Email REST API
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target='_blank' href='https://app.elasticemail.com/marketing/settings/new/manage-api'>here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target='_blank' href='https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme'>here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WebhookCreatePayload model module.
 * @module model/WebhookCreatePayload
 * @version 4.2.0
 */
class WebhookCreatePayload {
    /**
     * Constructs a new <code>WebhookCreatePayload</code>.
     * Create webhook payload
     * @alias module:model/WebhookCreatePayload
     * @param name {String} Filename
     * @param URL {String} URL of notification.
     */
    constructor(name, URL) { 
        
        WebhookCreatePayload.initialize(this, name, URL);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, URL) { 
        obj['Name'] = name;
        obj['URL'] = URL;
    }

    /**
     * Constructs a <code>WebhookCreatePayload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WebhookCreatePayload} obj Optional instance to populate.
     * @return {module:model/WebhookCreatePayload} The populated <code>WebhookCreatePayload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WebhookCreatePayload();

            if (data.hasOwnProperty('Name')) {
                obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
            }
            if (data.hasOwnProperty('URL')) {
                obj['URL'] = ApiClient.convertToType(data['URL'], 'String');
            }
            if (data.hasOwnProperty('NotifyOncePerEmail')) {
                obj['NotifyOncePerEmail'] = ApiClient.convertToType(data['NotifyOncePerEmail'], 'Boolean');
            }
            if (data.hasOwnProperty('NotificationForSent')) {
                obj['NotificationForSent'] = ApiClient.convertToType(data['NotificationForSent'], 'Boolean');
            }
            if (data.hasOwnProperty('NotificationForOpened')) {
                obj['NotificationForOpened'] = ApiClient.convertToType(data['NotificationForOpened'], 'Boolean');
            }
            if (data.hasOwnProperty('NotificationForClicked')) {
                obj['NotificationForClicked'] = ApiClient.convertToType(data['NotificationForClicked'], 'Boolean');
            }
            if (data.hasOwnProperty('NotificationForUnsubscribed')) {
                obj['NotificationForUnsubscribed'] = ApiClient.convertToType(data['NotificationForUnsubscribed'], 'Boolean');
            }
            if (data.hasOwnProperty('NotificationForAbuseReport')) {
                obj['NotificationForAbuseReport'] = ApiClient.convertToType(data['NotificationForAbuseReport'], 'Boolean');
            }
            if (data.hasOwnProperty('NotificationForError')) {
                obj['NotificationForError'] = ApiClient.convertToType(data['NotificationForError'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WebhookCreatePayload</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WebhookCreatePayload</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WebhookCreatePayload.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['Name'] && !(typeof data['Name'] === 'string' || data['Name'] instanceof String)) {
            throw new Error("Expected the field `Name` to be a primitive type in the JSON string but got " + data['Name']);
        }
        // ensure the json data is a string
        if (data['URL'] && !(typeof data['URL'] === 'string' || data['URL'] instanceof String)) {
            throw new Error("Expected the field `URL` to be a primitive type in the JSON string but got " + data['URL']);
        }

        return true;
    }


}

WebhookCreatePayload.RequiredProperties = ["Name", "URL"];

/**
 * Filename
 * @member {String} Name
 */
WebhookCreatePayload.prototype['Name'] = undefined;

/**
 * URL of notification.
 * @member {String} URL
 */
WebhookCreatePayload.prototype['URL'] = undefined;

/**
 * @member {Boolean} NotifyOncePerEmail
 */
WebhookCreatePayload.prototype['NotifyOncePerEmail'] = undefined;

/**
 * @member {Boolean} NotificationForSent
 */
WebhookCreatePayload.prototype['NotificationForSent'] = undefined;

/**
 * @member {Boolean} NotificationForOpened
 */
WebhookCreatePayload.prototype['NotificationForOpened'] = undefined;

/**
 * @member {Boolean} NotificationForClicked
 */
WebhookCreatePayload.prototype['NotificationForClicked'] = undefined;

/**
 * @member {Boolean} NotificationForUnsubscribed
 */
WebhookCreatePayload.prototype['NotificationForUnsubscribed'] = undefined;

/**
 * @member {Boolean} NotificationForAbuseReport
 */
WebhookCreatePayload.prototype['NotificationForAbuseReport'] = undefined;

/**
 * @member {Boolean} NotificationForError
 */
WebhookCreatePayload.prototype['NotificationForError'] = undefined;






export default WebhookCreatePayload;

