/**
 * Elastic Email REST API
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target='_blank' href='https://app.elasticemail.com/marketing/settings/new/manage-api'>here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target='_blank' href='https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme'>here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Webhook from '../model/Webhook';
import WebhookCreatePayload from '../model/WebhookCreatePayload';
import WebhookUpdatePayload from '../model/WebhookUpdatePayload';

/**
* Webhook service.
* @module api/WebhookApi
* @version 4.0.30
*/
export default class WebhookApi {

    /**
    * Constructs a new WebhookApi. 
    * @alias module:api/WebhookApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the webhookByPublicidDelete operation.
     * @callback module:api/WebhookApi~webhookByPublicidDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Webhook
     * Delete the specified notifications webhook. Required Access Level: ModifyWebNotifications
     * @param {String} publicid 
     * @param {module:api/WebhookApi~webhookByPublicidDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    webhookByPublicidDelete(publicid, callback) {
      let postBody = null;
      // verify the required parameter 'publicid' is set
      if (publicid === undefined || publicid === null) {
        throw new Error("Missing the required parameter 'publicid' when calling webhookByPublicidDelete");
      }

      let pathParams = {
        'publicid': publicid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apikey'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/webhook/{publicid}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the webhookByPublicidGet operation.
     * @callback module:api/WebhookApi~webhookByPublicidGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Webhook} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Load Webhook
     * Load notifications webhook details. Required Access Level: ViewWebNotifications
     * @param {String} publicid 
     * @param {module:api/WebhookApi~webhookByPublicidGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Webhook}
     */
    webhookByPublicidGet(publicid, callback) {
      let postBody = null;
      // verify the required parameter 'publicid' is set
      if (publicid === undefined || publicid === null) {
        throw new Error("Missing the required parameter 'publicid' when calling webhookByPublicidGet");
      }

      let pathParams = {
        'publicid': publicid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apikey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Webhook;
      return this.apiClient.callApi(
        '/webhook/{publicid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the webhookByPublicidPut operation.
     * @callback module:api/WebhookApi~webhookByPublicidPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Webhook} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Webhook
     * Update notification webhook. Required Access Level: ModifyWebNotifications
     * @param {String} publicid 
     * @param {module:model/WebhookUpdatePayload} webhookUpdatePayload 
     * @param {module:api/WebhookApi~webhookByPublicidPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Webhook}
     */
    webhookByPublicidPut(publicid, webhookUpdatePayload, callback) {
      let postBody = webhookUpdatePayload;
      // verify the required parameter 'publicid' is set
      if (publicid === undefined || publicid === null) {
        throw new Error("Missing the required parameter 'publicid' when calling webhookByPublicidPut");
      }
      // verify the required parameter 'webhookUpdatePayload' is set
      if (webhookUpdatePayload === undefined || webhookUpdatePayload === null) {
        throw new Error("Missing the required parameter 'webhookUpdatePayload' when calling webhookByPublicidPut");
      }

      let pathParams = {
        'publicid': publicid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apikey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Webhook;
      return this.apiClient.callApi(
        '/webhook/{publicid}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the webhookGet operation.
     * @callback module:api/WebhookApi~webhookGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Webhook>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Load Webhooks
     * Returns a list of notification webhooks. Required Access Level: ViewWebNotifications
     * @param {Object} opts Optional parameters
     * @param {Number} [limit] Maximum number of returned items.
     * @param {Number} [offset] How many items should be returned ahead.
     * @param {module:api/WebhookApi~webhookGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Webhook>}
     */
    webhookGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'limit': opts['limit'],
        'offset': opts['offset']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apikey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Webhook];
      return this.apiClient.callApi(
        '/webhook', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the webhookPost operation.
     * @callback module:api/WebhookApi~webhookPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Webhook} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add Webhook
     * Add a notification webhook. Required Access Level: ModifyWebNotifications
     * @param {module:model/WebhookCreatePayload} webhookCreatePayload 
     * @param {module:api/WebhookApi~webhookPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Webhook}
     */
    webhookPost(webhookCreatePayload, callback) {
      let postBody = webhookCreatePayload;
      // verify the required parameter 'webhookCreatePayload' is set
      if (webhookCreatePayload === undefined || webhookCreatePayload === null) {
        throw new Error("Missing the required parameter 'webhookCreatePayload' when calling webhookPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apikey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Webhook;
      return this.apiClient.callApi(
        '/webhook', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
