/**
 * Elastic Email REST API
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ElasticEmail);
  }
}(this, function(expect, ElasticEmail) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ElasticEmail.RecipientEvent();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RecipientEvent', function() {
    it('should create an instance of RecipientEvent', function() {
      // uncomment below and update the code to test RecipientEvent
      //var instance = new ElasticEmail.RecipientEvent();
      //expect(instance).to.be.a(ElasticEmail.RecipientEvent);
    });

    it('should have the property transactionID (base name: "TransactionID")', function() {
      // uncomment below and update the code to test the property transactionID
      //var instance = new ElasticEmail.RecipientEvent();
      //expect(instance).to.be();
    });

    it('should have the property msgID (base name: "MsgID")', function() {
      // uncomment below and update the code to test the property msgID
      //var instance = new ElasticEmail.RecipientEvent();
      //expect(instance).to.be();
    });

    it('should have the property fromEmail (base name: "FromEmail")', function() {
      // uncomment below and update the code to test the property fromEmail
      //var instance = new ElasticEmail.RecipientEvent();
      //expect(instance).to.be();
    });

    it('should have the property to (base name: "To")', function() {
      // uncomment below and update the code to test the property to
      //var instance = new ElasticEmail.RecipientEvent();
      //expect(instance).to.be();
    });

    it('should have the property subject (base name: "Subject")', function() {
      // uncomment below and update the code to test the property subject
      //var instance = new ElasticEmail.RecipientEvent();
      //expect(instance).to.be();
    });

    it('should have the property eventType (base name: "EventType")', function() {
      // uncomment below and update the code to test the property eventType
      //var instance = new ElasticEmail.RecipientEvent();
      //expect(instance).to.be();
    });

    it('should have the property eventDate (base name: "EventDate")', function() {
      // uncomment below and update the code to test the property eventDate
      //var instance = new ElasticEmail.RecipientEvent();
      //expect(instance).to.be();
    });

    it('should have the property channelName (base name: "ChannelName")', function() {
      // uncomment below and update the code to test the property channelName
      //var instance = new ElasticEmail.RecipientEvent();
      //expect(instance).to.be();
    });

    it('should have the property messageCategory (base name: "MessageCategory")', function() {
      // uncomment below and update the code to test the property messageCategory
      //var instance = new ElasticEmail.RecipientEvent();
      //expect(instance).to.be();
    });

    it('should have the property nextTryOn (base name: "NextTryOn")', function() {
      // uncomment below and update the code to test the property nextTryOn
      //var instance = new ElasticEmail.RecipientEvent();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "Message")', function() {
      // uncomment below and update the code to test the property message
      //var instance = new ElasticEmail.RecipientEvent();
      //expect(instance).to.be();
    });

    it('should have the property iPAddress (base name: "IPAddress")', function() {
      // uncomment below and update the code to test the property iPAddress
      //var instance = new ElasticEmail.RecipientEvent();
      //expect(instance).to.be();
    });

    it('should have the property poolName (base name: "PoolName")', function() {
      // uncomment below and update the code to test the property poolName
      //var instance = new ElasticEmail.RecipientEvent();
      //expect(instance).to.be();
    });

  });

}));
