/**
 * Elastic Email REST API
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target='_blank' href='https://app.elasticemail.com/marketing/settings/new/manage-api'>here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target='_blank' href='https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme'>here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ElasticEmail);
  }
}(this, function(expect, ElasticEmail) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ElasticEmail.Webhook();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Webhook', function() {
    it('should create an instance of Webhook', function() {
      // uncomment below and update the code to test Webhook
      //var instance = new ElasticEmail.Webhook();
      //expect(instance).to.be.a(ElasticEmail.Webhook);
    });

    it('should have the property webhookID (base name: "WebhookID")', function() {
      // uncomment below and update the code to test the property webhookID
      //var instance = new ElasticEmail.Webhook();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "Name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new ElasticEmail.Webhook();
      //expect(instance).to.be();
    });

    it('should have the property dateCreated (base name: "DateCreated")', function() {
      // uncomment below and update the code to test the property dateCreated
      //var instance = new ElasticEmail.Webhook();
      //expect(instance).to.be();
    });

    it('should have the property dateUpdated (base name: "DateUpdated")', function() {
      // uncomment below and update the code to test the property dateUpdated
      //var instance = new ElasticEmail.Webhook();
      //expect(instance).to.be();
    });

    it('should have the property URL (base name: "URL")', function() {
      // uncomment below and update the code to test the property URL
      //var instance = new ElasticEmail.Webhook();
      //expect(instance).to.be();
    });

    it('should have the property notifyOncePerEmail (base name: "NotifyOncePerEmail")', function() {
      // uncomment below and update the code to test the property notifyOncePerEmail
      //var instance = new ElasticEmail.Webhook();
      //expect(instance).to.be();
    });

    it('should have the property notificationForSent (base name: "NotificationForSent")', function() {
      // uncomment below and update the code to test the property notificationForSent
      //var instance = new ElasticEmail.Webhook();
      //expect(instance).to.be();
    });

    it('should have the property notificationForOpened (base name: "NotificationForOpened")', function() {
      // uncomment below and update the code to test the property notificationForOpened
      //var instance = new ElasticEmail.Webhook();
      //expect(instance).to.be();
    });

    it('should have the property notificationForClicked (base name: "NotificationForClicked")', function() {
      // uncomment below and update the code to test the property notificationForClicked
      //var instance = new ElasticEmail.Webhook();
      //expect(instance).to.be();
    });

    it('should have the property notificationForUnsubscribed (base name: "NotificationForUnsubscribed")', function() {
      // uncomment below and update the code to test the property notificationForUnsubscribed
      //var instance = new ElasticEmail.Webhook();
      //expect(instance).to.be();
    });

    it('should have the property notificationForAbuseReport (base name: "NotificationForAbuseReport")', function() {
      // uncomment below and update the code to test the property notificationForAbuseReport
      //var instance = new ElasticEmail.Webhook();
      //expect(instance).to.be();
    });

    it('should have the property notificationForError (base name: "NotificationForError")', function() {
      // uncomment below and update the code to test the property notificationForError
      //var instance = new ElasticEmail.Webhook();
      //expect(instance).to.be();
    });

    it('should have the property isEnabled (base name: "IsEnabled")', function() {
      // uncomment below and update the code to test the property isEnabled
      //var instance = new ElasticEmail.Webhook();
      //expect(instance).to.be();
    });

  });

}));
