/**
 * Elastic Email REST API
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ElasticEmail);
  }
}(this, function(expect, ElasticEmail) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ElasticEmail.ContactsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ContactsApi', function() {
    describe('contactsByEmailDelete', function() {
      it('should call contactsByEmailDelete successfully', function(done) {
        //uncomment below and update the code to test contactsByEmailDelete
        //instance.contactsByEmailDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('contactsByEmailGet', function() {
      it('should call contactsByEmailGet successfully', function(done) {
        //uncomment below and update the code to test contactsByEmailGet
        //instance.contactsByEmailGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('contactsByEmailPut', function() {
      it('should call contactsByEmailPut successfully', function(done) {
        //uncomment below and update the code to test contactsByEmailPut
        //instance.contactsByEmailPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('contactsDeletePost', function() {
      it('should call contactsDeletePost successfully', function(done) {
        //uncomment below and update the code to test contactsDeletePost
        //instance.contactsDeletePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('contactsExportByIdStatusGet', function() {
      it('should call contactsExportByIdStatusGet successfully', function(done) {
        //uncomment below and update the code to test contactsExportByIdStatusGet
        //instance.contactsExportByIdStatusGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('contactsExportPost', function() {
      it('should call contactsExportPost successfully', function(done) {
        //uncomment below and update the code to test contactsExportPost
        //instance.contactsExportPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('contactsGet', function() {
      it('should call contactsGet successfully', function(done) {
        //uncomment below and update the code to test contactsGet
        //instance.contactsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('contactsImportPost', function() {
      it('should call contactsImportPost successfully', function(done) {
        //uncomment below and update the code to test contactsImportPost
        //instance.contactsImportPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('contactsPost', function() {
      it('should call contactsPost successfully', function(done) {
        //uncomment below and update the code to test contactsPost
        //instance.contactsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
