/**
 * Elastic Email REST API
 * This API is based on the REST API architecture, allowing the user to easily manage their data with this resource-based approach.    Every API call is established on which specific request type (GET, POST, PUT, DELETE) will be used.    The API has a limit of 20 concurrent connections and a hard timeout of 600 seconds per request.    To start using this API, you will need your Access Token (available <a target=\"_blank\" href=\"https://app.elasticemail.com/marketing/settings/new/manage-api\">here</a>). Remember to keep it safe. Required access levels are listed in the given request’s description.    Downloadable library clients can be found in our Github repository <a target=\"_blank\" href=\"https://github.com/ElasticEmail?tab=repositories&q=%22rest+api%22+in%3Areadme\">here</a>
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@elasticemail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ElasticEmail);
  }
}(this, function(expect, ElasticEmail) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ElasticEmail.SecurityApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SecurityApi', function() {
    describe('securityApikeysByNameDelete', function() {
      it('should call securityApikeysByNameDelete successfully', function(done) {
        //uncomment below and update the code to test securityApikeysByNameDelete
        //instance.securityApikeysByNameDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityApikeysByNameGet', function() {
      it('should call securityApikeysByNameGet successfully', function(done) {
        //uncomment below and update the code to test securityApikeysByNameGet
        //instance.securityApikeysByNameGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityApikeysByNamePut', function() {
      it('should call securityApikeysByNamePut successfully', function(done) {
        //uncomment below and update the code to test securityApikeysByNamePut
        //instance.securityApikeysByNamePut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityApikeysGet', function() {
      it('should call securityApikeysGet successfully', function(done) {
        //uncomment below and update the code to test securityApikeysGet
        //instance.securityApikeysGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityApikeysPost', function() {
      it('should call securityApikeysPost successfully', function(done) {
        //uncomment below and update the code to test securityApikeysPost
        //instance.securityApikeysPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securitySmtpByNameDelete', function() {
      it('should call securitySmtpByNameDelete successfully', function(done) {
        //uncomment below and update the code to test securitySmtpByNameDelete
        //instance.securitySmtpByNameDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securitySmtpByNameGet', function() {
      it('should call securitySmtpByNameGet successfully', function(done) {
        //uncomment below and update the code to test securitySmtpByNameGet
        //instance.securitySmtpByNameGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securitySmtpByNamePut', function() {
      it('should call securitySmtpByNamePut successfully', function(done) {
        //uncomment below and update the code to test securitySmtpByNamePut
        //instance.securitySmtpByNamePut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securitySmtpGet', function() {
      it('should call securitySmtpGet successfully', function(done) {
        //uncomment below and update the code to test securitySmtpGet
        //instance.securitySmtpGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securitySmtpPost', function() {
      it('should call securitySmtpPost successfully', function(done) {
        //uncomment below and update the code to test securitySmtpPost
        //instance.securitySmtpPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
